### ISSUE TITLE
emphasis is unavoidable in certain common link attributes

### ISSUE THREAD

**Issue by spacehobo** [vim-pandoc/vim-pandoc-syntax#247] opened 2018-09-26 14:38 UTC
The way to make links in web pages open in new tabs is to set the `target="_blank"` attribute as in `<a href="https://github.com/vim-pandoc/vim-pandoc-syntax" target="_blank">`.  Unfortunately when I type `[vim pandoc syntax plugin](https://github.com/vim-pandoc/vim-pandoc-syntax){target="_blank"}` to achieve this, pandoc-syntax insists that I am beginning an italicised block with the _ and it continues on to the next link.

This makes a mess of my document, as suddenly the remainder of it is considered to be part of an italicised text stream instead of all the other structures it represents.  So far my best workaround has been to use `{target="_blank" foo="bar_"}` but it still renders incorrectly between the two underscores.

Pandoc itself handles this syntax correctly.

**Comment by alerque** [comment] 2019-11-17 21:31
Issue #290 is actually a duplicate of this, but since the description is a bit more complete as far as referencing the spec, I'm closing this in favor of that one. Please subscribe there to get notified when this is fixed.

**Closed by alerque** 2019-11-17 21:31 UTC
Labels: bug
